name: Build and Push  Case-Service Docker Images

on:
  push:
    paths:
      - hospital-management/**

jobs:
 
  build-push-case-service:
    runs-on: ubuntu-latest

    steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Perform google formatter check
      run: mvn com.spotify.fmt:fmt-maven-plugin:check

    - name: GitLeaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=.

    - name: OSS Scan
      run: mvn ossindex:audit
      continue-on-error: true

    - name: OWASP Scan
      if: false
      run: mvn org.owasp:dependency-check-maven:check
    
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

    - name: Build Docker Image for case-service
      run: docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/case-service:latest -f dockerfile .
      working-directory: hospital-management/case-service

    - name: Push Docker Image for case-service
      run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/case-service:latest
          



        
