name: Build and Push Docker Images

on:
  push:
    paths:
      - hospital-management/**

jobs:
          
  build-push-patient-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Build Docker Image for patient-service
        run: docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/patient-service:latest -f dockerfile .
        working-directory: hospital-management/patient-service

      - name: Push Docker Image for patient-service
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/patient-service:latest
